name = "backend"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-17"

[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "nivaro-auth"
database_id = "placeholder-for-real-deployment"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "nivaro-content"

# Production environment
[env.production]
name = "nivaro-backend"
vars = { ENVIRONMENT = "production" }

# Staging environment  
[env.staging]
name = "nivaro-backend-staging"
vars = { ENVIRONMENT = "staging" }
