# Cloudflare Workers deployment for Next.js

This file is required for deploying Next.js on Cloudflare Workers using next-on-pages.

name = "nivaro-frontend-staging"
type = "javascript"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2025-08-17"

[build]
command = "npx @cloudflare/next-on-pages@latest build"

[env.staging]
route = "https://nivaro-staging.arturmisiurev.workers.dev/*"

# Add any additional configuration as needed
